In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/HR_comma_sep (2).csv')

In [2]:
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [3]:
df1=['sales','salary']
df_final=pd.get_dummies(df,columns=df1,drop_first=True)

In [4]:
df1

['sales', 'salary']

In [5]:
df_final

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years  sales_RandD  sales_accounting  sales_hr  \
0                          0            0                 0         0   
1                          0            0                 0         0   
2                          0            0                 0         0   
3                          0            0                 0         0   
4                          0            0                 0         0   
...                      ...          ...               ...       ...   
14994                      0            0                 0         0   
14995                      0            0                 0         0   
14996                      0            0                 0         0   
14997                      0            0                 0         0   
14998                      0            0                 0         0   

       sales_management  sales_marketing  sales_product_mng  sales_sales  \
0                     0                0                  0            1   
1                     0                0                  0            1   
2                     0                0                  0            1   
3                     0                0                  0            1   
4                     0                0                  0            1   
...                 ...              ...                ...          ...   
14994                 0                0                  0            0   
14995                 0                0                  0            0   
14996                 0                0                  0            0   
14997                 0                0                  0            0   
14998                 0                0                  0            0   

       sales_support  sales_technical  salary_low  salary_medium  
0                  0                0           1              0  
1                  0                0           0              1  
2                  0                0           0              1  
3                  0                0           1              0  
4                  0                0           1              0  
...              ...              ...         ...            ...  
14994              1                0           1              0  
14995              1                0           1              0  
1499

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.


In [6]:
from sklearn.model_selection import train_test_split
X = df_final.drop(['left'],axis=1).values
y = df_final['left'].values

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [9]:
from keras.models import Sequential
from keras.layers import Dense
classifier=Sequential()
classifier.add(Dense(9,kernel_initializer="uniform",activation="relu",input_dim=18))
classifier.add(Dense(1,kernel_initializer="uniform",activation="sigmoid"))
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=["accuracy"])

In [10]:
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
1050/1050 [==============================] - 3s 2ms/step - loss: 0.4223 - accuracy: 0.7924
Epoch 2/100
1050/1050 [==============================] - 3s 3ms/step - loss: 0.2769 - accuracy: 0.8449
Epoch 3/100
1050/1050 [==============================] - 4s 4ms/step - loss: 0.2313 - accuracy: 0.9079
Epoch 4/100
1050/1050 [==============================] - 5s 5ms/step - loss: 0.2064 - accuracy: 0.9455
Epoch 5/100
1050/1050 [==============================] - 6s 5ms/step - loss: 0.1896 - accuracy: 0.9537
Epoch 6/100
1050/1050 [==============================] - 8s 8ms/step - loss: 0.1798 - accuracy: 0.9556
Epoch 7/100
1050/1050 [==============================] - 5s 5ms/step - loss: 0.1729 - accuracy: 0.9581
Epoch 8/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.1685 - accuracy: 0.9580
Epoch 9/100
1050/1050 [==============================] - 2s 2ms/step - loss: 0.1655 - accuracy: 0.9566
Epoch 10/100
1050/1050 [==============================] - 2s 2ms/step - l

In [11]:
y_pred = classifier.predict(X_test)
y_pred

141/141 [==============================] - 0s 1ms/step


array([[9.3165880e-01],
       [9.4679075e-01],
       [1.5007777e-04],
       ...,
       [9.8861784e-01],
       [1.9283002e-06],
       [8.0753048e-04]], dtype=float32)

In [12]:
y_pred = (y_pred > 0.5)
y_pred

array([[ True],
       [ True],
       [False],
       ...,
       [ True],
       [False],
       [False]])

In [13]:
from sklearn.metrics import accuracy_score
cm=accuracy_score(y_test,y_pred)
cm

0.9517777777777777

In [14]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[3299,  114],
       [ 103,  984]])